---
title: "linear models"
author: "Zakari L. Billo"
date: "2025-11-06"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)

knitr::opts_chunk$set(
  fig.width = 8,
  fig.height = 7,
  fig.align = "center",
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

data + cleaning 

```{r}
nyc_airbnb = 
  nyc_airbnb |>
  mutate(
    stars = review_scores_location / 2 
  ) |>
  rename(
    borough = neighbourhood_group
  ) |>
  filter(borough != "Staten Island") |>
  select(price, stars, borough, room_type, neighbourhood)
```

do regression

```{r}
fit = lm(price ~ stars + borough, data = nyc_airbnb)
```

do some additional cleaning  then refit

```{r}
nyc_airbnb = 
  nyc_airbnb |>
    mutate(
      borough = fct_infreq(borough),
      room_type = fct_infreq(room_type)
    )

fit = lm(price ~ stars + borough, data = nyc_airbnb)
```

summary of `lm`

```{r}
summary(fit)
names(summary(fit))
summary(fit)[["coefficients"]]
summary(fit)[["df"]]

fitted.values(fit)
resid(fit)
```

broom

```{r}
fit |>
  broom::tidy() |>
  mutate(
    term = str_replace(term, "borough", "Borough: ")) |>
  select(term, estimate, p.value) |>
  knitr::kable(digits = 3)
    
fit |>
  broom::glance()
```

## diagnostics

```{r}
nyc_airbnb |>
  modelr::add_residuals(fit)
```

